const INITIAL_APP_LOADING_AUTH_CHECK = "INITIAL_APP_LOADING_AUTH_CHECK";
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const REGISTER = "REGISTER";
const FORGOT_PASSWORD = "FORGOT_PASSWORD";
const RESET_PASSWORD = "RESET_PASSWORD";
